// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktftvenrykcuqswkfvxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0ZnR2ZW5yeWtjdXFzd2tmdnhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMTQyODYsImV4cCI6MjA3MTU5MDI4Nn0.VMPSwQQfwZEjvXo98gcXHK03vESCfiT1eKWnh3U8RVE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});